project_id = "zrqqptlzinowiwzxnbit"

[functions.create-checkout]
verify_jwt = false

[functions.get-checkout-session]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.send-contact-emails]
verify_jwt = false

[functions.send-checklist-emails]
verify_jwt = false

[functions.handle-email-events]
verify_jwt = false
