// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/get-plans.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
var plans = [
  {
    name: "Starter",
    monthlyPriceEur: 49,
    annualPriceEur: 490,
    bestFor: "Small businesses that need a professional website quickly",
    features: [
      "5-page professionally designed website",
      "Mobile-responsive design",
      "Hosting, SSL certificate and domain connection",
      "On-page SEO setup",
      "Contact and lead capture form",
      "Unlimited content updates",
      "Google Analytics connection"
    ]
  },
  {
    name: "Growth",
    monthlyPriceEur: 89,
    annualPriceEur: 890,
    bestFor: "Irish SMEs that need bookings and stronger local search support",
    features: [
      "Up to 10 professionally designed pages",
      "Online booking or appointment system",
      "Full SEO setup and keyword targeting",
      "Local search setup and optimisation",
      "Unlimited content updates",
      "Google Analytics and Search Console connection",
      "Priority support"
    ]
  },
  {
    name: "Pro",
    monthlyPriceEur: 149,
    annualPriceEur: 1490,
    bestFor: "Businesses that need advanced features, integrations and growth support",
    features: [
      "Unlimited pages and custom design",
      "Advanced SEO with monthly ranking report",
      "Live chat or WhatsApp widget",
      "Email marketing integration",
      "Unlimited content updates",
      "Monthly strategy report",
      "Custom integrations and advanced features"
    ]
  }
];
var get_plans_default = defineTool({
  name: "get_website_plans",
  title: "Get website plans",
  description: "List hellowebby's current website subscription plans, prices and included features.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ plans, annualSaving: "Two months free" }) }],
    structuredContent: { plans, annualSaving: "Two months free" }
  })
});

// src/lib/mcp/tools/submit-enquiry.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function projectUrl() {
  const value = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!value) throw new Error("Backend URL is not configured");
  return value;
}
function publishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const values = Object.values(parsed);
        const key = values.find(
          (value) => typeof value === "string" && value.trim().startsWith("sb_publishable_")
        );
        if (key) return key.trim();
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Backend publishable key is not configured");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("An authenticated account is required");
  return createClient(projectUrl(), publishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/submit-enquiry.ts
var submit_enquiry_default = defineTool2({
  name: "submit_website_enquiry",
  title: "Submit website enquiry",
  description: "Send a website enquiry to hellowebby for the signed-in caller after they confirm the details.",
  inputSchema: {
    name: z.string().trim().min(2).max(100).describe("Contact name"),
    phone: z.string().trim().max(40).optional().describe("Contact phone number"),
    company: z.string().trim().max(120).optional().describe("Business or company name"),
    message: z.string().trim().min(10).max(1e3).describe("Website requirements and questions"),
    plan: z.string().trim().max(150).optional().describe("Plan of interest, if known")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ name, phone, company, message, plan }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Please sign in before submitting an enquiry.");
    const email = ctx.getUserEmail();
    if (!email) throw new ToolError("Your signed-in account does not include an email address.");
    const client = supabaseForUser(ctx);
    const pricingPlan = plan || "Agent integration enquiry";
    const { error: insertError } = await client.from("form_submissions").insert({
      name,
      email,
      phone: phone || null,
      company: company || null,
      message,
      pricing_plan: pricingPlan
    });
    if (insertError) throw new ToolError("The enquiry could not be saved. Please try again.");
    const submissionId = crypto.randomUUID();
    const { error: emailError } = await client.functions.invoke("send-contact-emails", {
      body: {
        submissionId,
        name,
        email,
        phone: phone || null,
        company: company || null,
        message,
        pricing_plan: pricingPlan
      }
    });
    if (emailError) throw new ToolError("The enquiry was saved, but its email could not be sent. Please contact hello@hellowebby.com.");
    return {
      content: [{ type: "text", text: "Your enquiry was sent to hellowebby. The team will be in touch within a few days." }],
      structuredContent: { submitted: true, email, plan: pricingPlan }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zrqqptlzinowiwzxnbit";
var mcp_default = defineMcp({
  name: "hellowebby",
  title: "hellowebby",
  version: "0.1.0",
  instructions: "Use these tools to explain hellowebby's website plans and submit a website enquiry only after confirming the details with the caller.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_plans_default, submit_enquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
